# This is a basic workflow that is manually triggered
name: Manual deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      message:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Deploy message'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true
      environment:
        description: 'Environment to get the code deployed to'
        type: environment
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  deployToS3:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    environment: 
      name: "${{ github.event.inputs.environment }}"
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from the selected environment
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
        aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
        role-to-assume: '${{ secrets.AWS_ROLE_TO_ASSUME }}'
        role-duration-seconds: 1200
        aws-region: us-east-1
    - name: Add NPM Token
      run: 'echo "//registry.npmjs.org/:_authToken=${{ secrets.NpmAuthToken }}" > .npmrc'
    - name: Install Dependencies
      run: |
        yarn install
    - name: Branch name
      run: echo running on branch ${GITHUB_REF//[a-zA-Z\/]/}
    - name: Add Version Number
      run: 'echo "{ \"version\" : \"${GITHUB_REF//[a-zA-Z\/]/}\" }" > ./src/version.json'
    - name: Build App
      run: |
        yarn build
    - name: Copy files to the dev account with the AWS CLI
      run: |
        aws s3 sync --delete --acl public-read ./build s3://"${{ secrets.AWS_S3_BUCKET_NAME }}"
        aws s3 cp --acl public-read --cache-control="max-age=100, no-cache, no-store, must-revalidate" ./build/index.html s3://"${{ secrets.AWS_S3_BUCKET_NAME }}"
    - name: Send GitHub Action trigger data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.21.0
      env:
        SLACK_WEBHOOK_URL: '${{ secrets.SLACK_WEBHOOK_URL }}'
      with:
        payload: |
          {
            "environment": "${{ github.event.inputs.environment }}",
            "message": "${{ github.event.inputs.message }}",
            "status": "${{ job.status }}"
          }

  slackNotification:
    runs-on: ubuntu-latest
    environment: 
      name: "${{ github.event.inputs.environment }}"
    steps:
    - name: Send GitHub Action trigger data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.21.0
      env:
        SLACK_WEBHOOK_URL: '${{ secrets.SLACK_WEBHOOK_URL }}'
      with:
        payload: |
          {
            "environment": "${{ github.event.inputs.environment }}",
            "message": "${{ github.event.inputs.message }}",
            "status": "In Progress"
          }
